// Generated by ts-to-zod
import { z } from 'zod';
import type { IModActionEntity, IUsernameChangeEntity } from './DynamoDBInterfaces';
import { type IDeckDataEntity, ModActionDefinitions, ModActionType, UsernameChangeSource } from './DynamoDBInterfaces';

export const IUserDataEntitySchema = z.object({
    id: z.string(),
    username: z.string(),
    preferences: z.record(z.any()).optional(),
});

export const IMatchupStatEntitySchema = z.object({
    leaderId: z.string(),
    baseId: z.string(),
    wins: z.number(),
    losses: z.number(),
    draws: z.number(),
});

export const IDeckStatsEntitySchema = z.object({
    wins: z.number(),
    losses: z.number(),
    draws: z.number(),
    statsByMatchup: z.array(IMatchupStatEntitySchema).optional(),
});
export const IDeckDataEntitySchema = z.object({
    id: z.string(),
    userId: z.string(),
    deck: z.object({
        leader: z.object({
            id: z.string(),
        }),
        secondLeader: z.object({
            id: z.string(),
        }).optional(),
        base: z.object({
            id: z.string(),
        }),
        name: z.string(),
        favourite: z.boolean(),
        deckLink: z.string(),
        deckLinkID: z.string(),
        source: z.string().optional(),
    }),
    stats: IDeckStatsEntitySchema.optional(),
}) as z.ZodType<IDeckDataEntity>;

// generated by chat-gpt
export const ServerRoleUsersListsSchema = z.object({
    admins: z.array(z.string().uuid()),
    developers: z.array(z.string().uuid()),
    moderators: z.array(z.string().uuid()),
});

export const ModActionSubmitSchema = z.object({
    playerId: z.string().min(1, 'playerId is required'),
    actionType: z.nativeEnum(ModActionType),
    durationDays: z.number().positive()
        .nullable()
        .optional(),
    note: z.string().optional(),
}).refine(
    (data) => {
        const requiresDuration = ModActionDefinitions[data.actionType].requiresDuration;
        const hasDuration = typeof data.durationDays === 'number' && data.durationDays > 0;
        return requiresDuration === hasDuration;
    },
    (data) => ({
        message: ModActionDefinitions[data.actionType].requiresDuration
            ? `durationDays is required and must be positive for ${data.actionType} actions`
            : `durationDays is not valid for ${data.actionType} actions`,
        path: ['durationDays'],
    })
)
    .refine(
        (data) => {
            if (!ModActionDefinitions[data.actionType].requiresNote) {
                return true;
            }
            return typeof data.note === 'string' && data.note.trim().length > 0;
        },
        (data) => ({ message: `note is required for ${data.actionType} actions`, path: ['note'] })
    );

export const ModActionCancelSchema = z.object({
    modActionId: z.string().min(1, 'modActionId is required'),
    playerId: z.string().min(1, 'playerId is required'),
});

export const FindUserSchema = z.object({
    searchQuery: z.string().min(1, 'searchQuery is required'),
});

export const ServerSettingsUpdateSchema = z.object({
    gamesEnabled: z.boolean().optional(),
    maintenanceMessage: z.string().max(500, 'maintenanceMessage must be 500 characters or fewer')
        .optional(),
}).refine(
    (data) => data.gamesEnabled !== undefined || data.maintenanceMessage !== undefined,
    { message: 'At least one of gamesEnabled or maintenanceMessage is required' }
);

export const ModActionEntitySchema = z.object({
    id: z.string(),
    playerId: z.string(),
    actionType: z.nativeEnum(ModActionType),
    durationDays: z.number().positive()
        .optional(),
    note: z.string().optional(),
    moderatorId: z.string(),
    moderatorUsername: z.string(),
    createdAt: z.string(),
    startedAt: z.string().optional(),
    expiresAt: z.string().optional(),
    cancelledAt: z.string().optional(),
    cancelledById: z.string().optional(),
    cancelledByUsername: z.string().optional(),
}) as z.ZodType<IModActionEntity>;

export const UsernameChangeEntitySchema = z.object({
    id: z.string(),
    playerId: z.string(),
    previousUsername: z.string().nullable(),
    newUsername: z.string(),
    source: z.nativeEnum(UsernameChangeSource),
    relatedModActionId: z.string().optional(),
    createdAt: z.string(),
}) as z.ZodType<IUsernameChangeEntity>;